import { StocksType } from '../models';

// Mock data for stock prices
export const stocks: StocksType[] = [
  { symbol: 'AAPL', price: 150.25, lastPrice: 148.2, sector: 'Technology' },
  { symbol: 'GOOGL', price: 2800.1, lastPrice: 1810.35, sector: 'Technology' },
  { symbol: 'MSFT', price: 305, lastPrice: 303.2, sector: 'Technology' },
  {
    symbol: 'AMZN',
    price: 3400.5,
    lastPrice: 3600.7,
    sector: 'Consumer Discretionary',
  },
  {
    symbol: 'TSLA',
    price: 720.1,
    lastPrice: 700.5,
    sector: 'Consumer Discretionary',
  },
  { symbol: 'FB', price: 370.2, lastPrice: 370.2, sector: 'Technology' },
  {
    symbol: 'NFLX',
    price: 580.75,
    lastPrice: 590.4,
    sector: 'Communication Services',
  },
  { symbol: 'NVDA', price: 220.1, lastPrice: 218.4, sector: 'Technology' },
  {
    symbol: 'BABA',
    price: 180.4,
    lastPrice: 175.2,
    sector: 'Consumer Discretionary',
  },
  { symbol: 'INTC', price: 55.3, lastPrice: 54.7, sector: 'Technology' },
  { symbol: 'AMD', price: 105.1, lastPrice: 102.4, sector: 'Technology' },
  { symbol: 'IBM', price: 142, lastPrice: 143.2, sector: 'Technology' },
  { symbol: 'ORCL', price: 88.7, lastPrice: 88.7, sector: 'Technology' },
  { symbol: 'CSCO', price: 56.5, lastPrice: 57.8, sector: 'Technology' },
  { symbol: 'ADBE', price: 660.2, lastPrice: 645.7, sector: 'Technology' },
  { symbol: 'UBER', price: 48.3, lastPrice: 50.4, sector: 'Technology' },
  { symbol: 'LYFT', price: 58.9, lastPrice: 60.1, sector: 'Technology' },
  { symbol: 'SQ', price: 240.1, lastPrice: 245.8, sector: 'Technology' },
  { symbol: 'PYPL', price: 270.3, lastPrice: 275.9, sector: 'Technology' },
  {
    symbol: 'TWTR',
    price: 72.5,
    lastPrice: 70.8,
    sector: 'Communication Services',
  },
  {
    symbol: 'SNAP',
    price: 75.2,
    lastPrice: 73.6,
    sector: 'Communication Services',
  },
  {
    symbol: 'SPOT',
    price: 220.9,
    lastPrice: 215.2,
    sector: 'Communication Services',
  },
  { symbol: 'SHOP', price: 1450.4, lastPrice: 1420.6, sector: 'Technology' },
  { symbol: 'ZM', price: 360.1, lastPrice: 350.3, sector: 'Technology' },
  { symbol: 'CRM', price: 250.9, lastPrice: 248.5, sector: 'Technology' },
  {
    symbol: 'PINS',
    price: 65.4,
    lastPrice: 65.4,
    sector: 'Communication Services',
  },
  { symbol: 'DOCU', price: 290.8, lastPrice: 290.8, sector: 'Technology' },
  { symbol: 'SQ', price: 245.3, lastPrice: 250.2, sector: 'Technology' },
  {
    symbol: 'DIS',
    price: 180.4,
    lastPrice: 175.7,
    sector: 'Communication Services',
  },
  { symbol: 'WMT', price: 142.2, lastPrice: 145.3, sector: 'Consumer Staples' },
];

export const stocksPart2: StocksType[] = [
  { symbol: 'PEP', price: 155.4, lastPrice: 153.2, sector: 'Consumer Staples' },
  { symbol: 'KO', price: 58.3, lastPrice: 57.9, sector: 'Consumer Staples' },
  {
    symbol: 'MCD',
    price: 230.5,
    lastPrice: 232.7,
    sector: 'Consumer Discretionary',
  },
  { symbol: 'PG', price: 140.2, lastPrice: 138.8, sector: 'Consumer Staples' },
  {
    symbol: 'TGT',
    price: 245.1,
    lastPrice: 242.5,
    sector: 'Consumer Discretionary',
  },
  {
    symbol: 'HD',
    price: 325.7,
    lastPrice: 321.9,
    sector: 'Consumer Discretionary',
  },
  {
    symbol: 'COST',
    price: 465.4,
    lastPrice: 460.8,
    sector: 'Consumer Staples',
  },
  {
    symbol: 'NKE',
    price: 145.6,
    lastPrice: 143.5,
    sector: 'Consumer Discretionary',
  },
  { symbol: 'V', price: 230.9, lastPrice: 225.3, sector: 'Financials' },
  { symbol: 'MA', price: 360.4, lastPrice: 350.7, sector: 'Financials' },
  { symbol: 'XOM', price: 55.1, lastPrice: 54.3, sector: 'Energy' },
  { symbol: 'CVX', price: 105.8, lastPrice: 103.4, sector: 'Energy' },
  { symbol: 'JPM', price: 160.7, lastPrice: 158.9, sector: 'Financials' },
  { symbol: 'BAC', price: 41.5, lastPrice: 40.9, sector: 'Financials' },
  { symbol: 'GS', price: 380.3, lastPrice: 375.1, sector: 'Financials' },
  { symbol: 'C', price: 70.2, lastPrice: 68.7, sector: 'Financials' },
  { symbol: 'WFC', price: 47.6, lastPrice: 46.9, sector: 'Financials' },
  { symbol: 'BA', price: 230.4, lastPrice: 225.2, sector: 'Industrials' },
  { symbol: 'CAT', price: 205.9, lastPrice: 202.1, sector: 'Industrials' },
  { symbol: 'MMM', price: 175.8, lastPrice: 174.2, sector: 'Industrials' },
];
